#pragma once

#define WM_APP_SHOW_OVERLAY (WM_USER + 12)
#define WM_APP_ENDPOINT_CHANGE (WM_USER + 13)
#define WM_APP_NOTIFICATION_ICON (WM_USER + 14)
#define WM_APP_HOTKEY_PRESSED (WM_USER + 15)
#define WM_APP_QUIT_PLEASE (WM_USER + 16)    // 0x0410
