#pragma once

#define WM_VOLUMECHANGE (WM_USER + 12)
#define WM_ENDPOINTCHANGE (WM_USER + 13)
#define WM_NOTIFICATION_ICON (WM_USER + 14)
#define WM_HOTKEY_PRESSED (WM_USER + 15)
#define WM_MIC_STATE_CHANGED (WM_USER + 16)
