#pragma once

#define FIRMWARE_VERSION 0x0100

#define BOOTLOADER_FLASH_LED_COUNT 20
#define BOOTLOADER_FLASH_LED_SPEED 0x80

#define BOOT_FLASH_LED_COUNT 10
#define BOOT_FLASH_LED_SPEED 0x40

#define BOOTLOADER_BUTTON_DELAY 0x2000    // about 30 seconds
// #define BOOTLOADER_BUTTON_DELAY 0x80

void led_set_flash();